### ISSUE TITLE
DOCTYPE / DTD path is invalid in --xunit output (Problems during the conversion into JUnit)

### ISSUE THREAD

**Issue by amerikan** [casperjs/casperjs#1528]
Getting path issues when running in Jenkins.

```shell
[xUnit] [ERROR] - Validation error on input
ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:183)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.jenkinsci.plugins.xunit.exception.XUnitException: Validation error on input
	at org.jenkinsci.plugins.xunit.service.XUnitValidationService.validateInputFile(XUnitValidationService.java:77)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:132)
	... 16 more
Caused by: org.jenkinsci.lib.dtkit.util.validator.ValidationException: Validation error
	at org.jenkinsci.lib.dtkit.util.validator.ValidationService.processValidation(ValidationService.java:136)
	at org.jenkinsci.lib.dtkit.model.AbstractOutputMetric.validate(AbstractOutputMetric.java:62)
	at org.jenkinsci.plugins.xunit.types.JUnitInputMetric.validateInputFile(JUnitInputMetric.java:65)
	at org.jenkinsci.plugins.xunit.service.XUnitValidationService.validateInputFile(XUnitValidationService.java:66)
	... 17 more
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/workspace/PortalDev/testsuites (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1305)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1271)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1167)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:155)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.jenkinsci.lib.dtkit.util.validator.ValidationService.processValidation(ValidationService.java:124)
	... 20 more
```

See https://github.com/n1k0/casperjs/issues/1458#issuecomment-209021781 and on wards for more info.

**Comment by amerikan** [comment]
| phantom 1.9.8 | phantom 2.1.1
------------ | :-------------: |  :-------------
casper 1.1.0-beta3 | :white_check_mark: Works | :heavy_multiplication_x: Incompatible version
casper 1.1.0-beta4 | :white_check_mark: Works | :x: invalid junit
casper 1.1.0-beta5 | :white_check_mark: Works | :x: invalid junit
casper 1.1.0 | :x: path exception | :x: path exception

**Comment by mickaelandrieu** [comment]
> Caused by: java.io.FileNotFoundException: /var/lib/jenkins/workspace/PortalDev/testsuites (No such file or directory)

@amerikan can you give us a diff of a xunit report OK / NOK ? this shouldn't reveal on which project your works but probably show us what is broken :)

**Comment by amerikan** [comment]
> Also, can you report (again, sorry), the command used in jenkins ? 

```bash
casperjs test tests/suite/ --includes=tests/routines.js --rooturl=http://example.org:80 --timeout=60 --ignore-ssl-errors=yes --xunit=log.xml
```

**Comment by amerikan** [comment]
@mickaelandrieu And to add, @istr noticed this: https://github.com/n1k0/casperjs/issues/1458#issuecomment-209046762

**Comment by BIGjuevos** [comment]
By chance, could this be related to #1535?

**Comment by istr** [comment]
@amerikan I published 1.1.1 (to npm too) as a hot-fix for #1535. Please check if this resolves your issue. Thank you.

**Comment by amerikan** [comment]
Nope, same issue when trying with 1.1.1.
```
+ phantomjs --version
1.9.8
+ casperjs --version
1.1.1


[32;1mResult log stored in log.xml                                                    [0m
Build step 'Execute shell' marked build as failure
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - 1 test report file(s) were found with the pattern 'log.xml' relative to '/var/lib/jenkins/workspace/PortalDev' for the testing framework 'JUnit'.
[xUnit] [ERROR] - Validation error on input
ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:183)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.jenkinsci.plugins.xunit.exception.XUnitException: Validation error on input
	at org.jenkinsci.plugins.xunit.service.XUnitValidationService.validateInputFile(XUnitValidationService.java:77)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:132)
	... 16 more
Caused by: org.jenkinsci.lib.dtkit.util.validator.ValidationException: Validation error
	at org.jenkinsci.lib.dtkit.util.validator.ValidationService.processValidation(ValidationService.java:136)
	at org.jenkinsci.lib.dtkit.model.AbstractOutputMetric.validate(AbstractOutputMetric.java:62)
	at org.jenkinsci.plugins.xunit.types.JUnitInputMetric.validateInputFile(JUnitInputMetric.java:65)
	at org.jenkinsci.plugins.xunit.service.XUnitValidationService.validateInputFile(XUnitValidationService.java:66)
	... 17 more
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/workspace/PortalDev/testsuites (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1305)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1271)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1167)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:155)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.jenkinsci.lib.dtkit.util.validator.ValidationService.processValidation(ValidationService.java:124)
	... 20 more
```

**Comment by istr** [comment]
Ok, now I have an idea what the root cause is: the XML parser tries to validate. So this is unrelated to #1535.

Output with 1.1-beta5
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites xmlns="http://www.w3.org/1999/xhtml" time="1.568">
  <testsuite name="Study" tests="2" failures="1" errors="0" time="1.568" timestamp="2016-04-19T21:39:03.635Z" package="suite/demo">
    <testcase name="this passes" classname="suite/demo" time="1.567"></testcase>
    <testcase name="this fails" classname="suite/demo" time="0.001"><failure type="assert">this fails</failure></testcase>
    <system-out></system-out>
  </testsuite></testsuites>
```

Output with 1.1.1
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casperjs PUBLIC "-//CasperJS//XUnit Test Results" "testsuites">
<testsuites time="1.987">
  <testsuite name="Study" tests="2" failures="1" errors="0" time="1.987" timestamp="2016-04-19T21:36:46.368Z" package="suite/demo">
  <testcase name="this passes" classname="suite/demo" time="1.986"/>
  <testcase name="this fails" classname="suite/demo" time="0.001"><failure type="assert"><![CDATA[this fails]]></failure></testcase>
  <system-out><![CDATA[]]></system-out>
  </testsuite>
</testsuites>
```

The problem is the ```DOCTYPE``` -- the validating parser tries to find the DTD under ```"testsuites"``` relative to the xml file path. This fails.

@BIGjuevos any reason to inject the (invalid/made up) DOCTYPE?

**Comment by BIGjuevos** [comment]
@istr I couldn't get the xmlDocument generation system to work happily without it.  Creation of a new document type was required to be able to generate a document that contained properly formatted CDATA.

I see two solutions:
1. It feels a bit hacky, but, we could just remove the doctype after string generation if it is causing issues.  I don't know the implications of this.
2. Change the generation to be `null` instead of `testsuites`.

**Comment by istr** [comment]
But the document type is [completely optional as per spec](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocument).

If I remove the docType from the ```createDocument``` call, this is the output both on PhantomJS 1.9.7 and 2.1.1 (and it includes CDATA sections):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites time="0.308">
  <testsuite name="Study" tests="2" failures="1" errors="0" time="0.308" timestamp="2016-04-20T07:29:48.049Z" package="suite/demo">
    <testcase name="this passes" classname="suite/demo" time="0.307"/><testcase name="this fails" classname="suite/demo" time="0.001"><failure type="assert"><![CDATA[this fails]]></failure></testcase>
    <system-out><![CDATA[]]></system-out>
  </testsuite>
</testsuites>
```

See PR #1546.

Could you elaborate how / why this fails and/or failed for you?

**Comment by BIGjuevos** [comment]
It has less to do with XML and more with my unfamiliarity with that section of the code at the time. I'm sure this was human error on my part due to a false assumption I had. I'm glad to see it isn't required at all.

**Comment by Northys** [comment]
@BIGjuevos thank you for merging, it caused issues for me as well. is there any way how can I install casperjs from master before you create new alpha/beta/whatever release tag, please?
@istr good job!

**Comment by istr** [comment]
If you are installing from ZIP, just open https://github.com/casperjs/casperjs and click "download ZIP", direct link https://github.com/casperjs/casperjs/archive/master.zip. If you are using npm, install from git target ```npm install https://github.com/casperjs/casperjs```, see https://docs.npmjs.com/cli/install.

**Comment by letsenzoy** [comment]
Having the same issue

**Comment by BIGjuevos** [comment]
@letsenzoy Have you looked at the newer versions of CasperJS like 1.1.1?

This issue was solved.

**Comment by BIGjuevos** [comment]
@letsenzoy In the event you've found a new bug, please open up a new issue and provide us with some steps to replicate.

**Comment by letsenzoy** [comment]
We are using casperjs 1.1.1 and PhantomJS 2.1.1 on our Jenkins Server. I am running
 cmd, 
"casperjs test --user=#{user} --run_test=#{test} --engine=slimerjs --xunit=#{log_file_path} --includes=#{path}"

This is the Xunit Configuration on Jenkins,
<img width="1158" alt="screen shot 2016-07-13 at 12 13 47 pm" src="https://cloud.githubusercontent.com/assets/9688939/16812663/b900ea14-48f3-11e6-8f5b-61a7193626f3.png">

**Comment by BIGjuevos** [comment]
You say you are using PhantomJS, but in your test command you are specifying `slimerjs`?

**Comment by letsenzoy** [comment]
Sorry, it is SlimerJS 0.9.6
