### ISSUE TITLE
local variable 'sys_path' referenced before assignment

### ISSUE THREAD

**Issue by vinayinfo** [casperjs/casperjs#1924]
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/circleci/python/2.7.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/CCC/apps/campaign/models.py", line 19, in <module>
    from screamshot.utils import casperjs_capture
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/screamshot/utils.py", line 100, in <module>
    CASPERJS_CMD = casperjs_command()
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/screamshot/utils.py", line 80, in casperjs_command
    msg = "%s binary cannot be found in PATH (%s)" % (method, sys_path)
UnboundLocalError: local variable 'sys_path' referenced before assignment

((and (cd "/home/ubuntu/CCC") (group (pipe (echo "'import json;from django.conf import settings;print('\\''OUT: '\\'' + settings.TEST_RUNNER)'") (python manage.py shell))))) returned exit code 1

**Comment by kensoh** [comment]
Hi @vinayinfo can you try with the [latest CasperJS v1.1.4-1](https://github.com/casperjs/casperjs/archive/1.1.4-1.zip)? Above error seems to be triggered from Python, and CasperJS works for me on macOS or Linux with Python v2.7 and v3.X.

**Comment by vinayinfo** [comment]
@kensoh I am still getting same error. I am using below command.
$ git clone git://github.com/casperjs/casperjs.git
$ cd casperjs
$ ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs

**Comment by kensoh** [comment]
Hi @vinayinfo following works for me, can you share if below works? Looks like maybe environmental difference in OS or Python setup. Also copying @jefleponot CasperJS maintainer.

```
TA:~ kensoh$ cd Desktop/
TA:Desktop kensoh$ git clone git://github.com/casperjs/casperjs.git
Cloning into 'casperjs'...
remote: Counting objects: 15694, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 15694 (delta 0), reused 1 (delta 0), pack-reused 15690
Receiving objects: 100% (15694/15694), 7.55 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (10580/10580), done.
TA:Desktop kensoh$ cd casperjs/bin/
TA:bin kensoh$ ll
total 104
-rwxr-xr-x  1 kensoh  staff  16979 May 10 02:09 bootstrap.js
-rwxr-xr-x  1 kensoh  staff   5192 May 10 02:09 casperjs
-rwxr-xr-x  1 kensoh  staff   7680 May 10 02:09 casperjs.exe
-rwxr-xr-x  1 kensoh  staff   9708 May 10 02:09 casperjs.js
-rw-r--r--  1 kensoh  staff    463 May 10 02:09 usage.txt
TA:bin kensoh$ ./casperjs --version
1.1.4
TA:bin kensoh$ python --version
Python 2.7.10
```

**Comment by kensoh** [comment]
Closing this for now but do continue the discussion if there's new inputs!
