### ISSUE TITLE
Cli tests are broken on Windows

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#996]
refs https://github.com/n1k0/casperjs/pull/991#issuecomment-50878475

Many failures trying to use `SIGALRM` like that:
```
======================================================================
ERROR: test_help (__main__.BasicCommandsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/clitests/runtests.py", line 31, in f2
    old_handler = signal.signal(signal.SIGALRM, timeout_handler)
AttributeError: 'module' object has no attribute 'SIGALRM'
```

then these errors:
```
======================================================================
ERROR: test_xunit_report_failing (__main__.XUnitReportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/clitests/runtests.py", line 436, in test_xunit_report_failing
    self.runCommand(command, failing=True)
  File "tests/clitests/runtests.py", line 54, in runCommand
    return subprocess.check_output(cmd_args).strip().decode('utf-8')
  File "c:\Python27\lib\subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "c:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

======================================================================
ERROR: test_xunit_report_passing (__main__.XUnitReportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/clitests/runtests.py", line 430, in test_xunit_report_passing
    self.runCommand(command, failing=False)
  File "tests/clitests/runtests.py", line 54, in runCommand
    return subprocess.check_output(cmd_args).strip().decode('utf-8')
  File "c:\Python27\lib\subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "c:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

----------------------------------------------------------------------
```

**Comment by BIGjuevos** [comment]
From what I can tell, we've got windows versions operating appropriately.

**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
